### ISSUE TITLE
text size

### ISSUE THREAD

**Issue by linuxgirl22** [EyeOdin/Pigment.O#1]
Hello, just to ask if the adjustable and scalable UI includes text size. I had a quick try of Pigment.O but couldn't see where things were, with the text being small. I'm on the latest Mint Mate, 27-inch monitor, Krita v5 (so was able to scale up the overall text to sans serif 13) and hi-dpi is selected.

**Comment by linuxgirl22** [comment]
I can see responses are happening on the krita forum, but I try to be signed up to the least online sites possible (github sign-up was before going more offline) ... text is too small, especially for such a complicated plugin, and am very happy with current setup anyway.

**Comment by EyeOdin** [comment]
I did a update just now.
There were 2 widgets that where propagating font size when they shouldn't.
Now it should be display the same font size as Krita.

**Comment by linuxgirl22** [comment]
That's awesome: thanks so much! :-) I appreciate your work on this; looks really cool from the screenshots. Will add it now.

**Comment by linuxgirl22** [comment]
I saw your post on the krita forum about being concerned how the text alteration may behave on linux. I'm thrilled personally that it shows text at size 13, but it does require Pigment-O to be dragged to larger in order to read the words fully and sort settings, then it can be resized back down and looks really good. I'll try to add pictures now (a lot of privacy settings!) ... 

![text size 1](https://user-images.githubusercontent.com/35760727/124851237-0eba9a80-df9a-11eb-9b34-d40a0b3a7e5f.png)

![text size 2](https://user-images.githubusercontent.com/35760727/124851247-14b07b80-df9a-11eb-93a8-56f4cab90401.png)

Success! Hope this feedback is helpful, and thanks again.

**Comment by EyeOdin** [comment]
oh your welcome. font size has been a issue I have been trying to get right for a while now. i thought it would be worse it looks kinda similar as it should be compared to my end.

but on linux everyone seems to see different things so it is hard to have some ground when I am on Windows that is different from all Linux users. I wanted to make a super tight UI originally but then I started to make too many options and started to need text.....if I could there would be no text but pigmento does so many different things I cant cut it out.

I still want to make this section better but I want to make a pop up window that communicates but making that still goes over my head.

**Comment by linuxgirl22** [comment]
The font's really great, and it's also easy to put Pigment.O into the side docker and just widen the side panel when needed, for making any changes. And, yes, it must be difficult to know exactly how the changes may look, for sure. The options within Pigment.O are great ... e.g. I used to really like clip studio's intermediate colours docker, had tried out the colour spheres software that's shown in the krita thread, and had been holding back from adding the two dockers for gamut use (to try to not fill up space too much with dockers)... to find all these, and more, in Pigment.O is quite something! Good to have the text prompts too; very neat, easy to read, and easy to hide. Can tell some very thorough work has gone into Pigment.O, that's so entirely beyond my level of tech ability, lol, so I'm confident you'll be fine with the pop up window.
