### ISSUE TITLE
How to choose a custom model?

### ISSUE THREAD

**Issue by imh1kiko** [EyeOdin/Pigment.O#15]
From what I'm seeing, you can set a custom OBJ model. I've tried looking around in settings (set it to "user"), and panel is active, but for the life of me, I can't find a place to change it. I've even tried to drag it in, but to no avail.

So the question is, how do you load a custom obj model?

**Comment by EyeOdin** [comment]
if you ever had READ the manual you would know the answer to all your questions ... and you would also know it is NOT a OBJ file although it was initially intended to be that.
