### ISSUE TITLE
Harmony picker on wheel is broken for Krita 5.1.1

### ISSUE THREAD

**Issue by fumoshi1** [EyeOdin/Pigment.O#16]
Krita Version: 5.1.1
OS: Windows 10

It worked like a charm before upgrading Krita, i am not considering to downgrade krita to a previous version (even for that case this is a potential issue). This looks like some compatibility issue but I am not so sure

**The Issue**

Basically the control lines to choose different colors in a color harmony scheme are broken, it's showing only one line (like the monochromatic harmony) regardless of what option I choose on "Harmony"

**What I did to try to workaround it**

I tried to fix this uninstalling the plugin (wiping pigment_o plugin folder under pykrita), wiping out Pigment.O config from kritarc file, and reinstalling the plugin. but the issue persists.

**Is there something I could do to debug it?**

I wonder if there is some method to enable some login so I can find out if there is some runtime issue or something (I can code some python, perhaps if I find the issue I may send some pull request)

Screen capture to show the issue more or less

![brokenharmonywheel](https://user-images.githubusercontent.com/85447407/194436195-1b2f4094-ff0c-4669-92c5-ead5b72465d2.jpg)

**Comment by EyeOdin** [comment]
well if you actually activate HArmony you would see it. but dont use RYB wheel with harmony either way that is a known bug but only be fixed on the remake.
