### ISSUE TITLE
QWidget's geometry() method is overridden.

### ISSUE THREAD

**Issue by Aqaao** [EyeOdin/Pigment.O#22]
QWidget.geometry is qt method address.

https://doc.qt.io/qt-6/qwidget.html#geometry-prop

https://github.com/EyeOdin/Pigment.O/blob/8acee1b00283cd4e10085a5b567e7ce661c06fc5/pigment_o/pigment_o_docker.py#L700

This may lead to potential bug.

Like this.
https://github.com/Aqaao/DockerUnderCursor/issues/4

**Comment by EyeOdin** [comment]
but is not my Nomeclature different on a straight forward case ?
geometry != Geometry

and Geometry is a class I created I am importing it above
and I still call widgets geometry correctly for history and menu_mode_press

**Comment by Aqaao** [comment]
OK. This is not a serious problem. I found `QWidget.geometry(widget)` can directly call parent method.
