### ISSUE TITLE
Color history not updating

### ISSUE THREAD

**Issue by JoseConseco** [EyeOdin/Pigment.O#7]
Hi, I'm using krita 5.0
After enabling color history in Pigment.O - I cannot see it being update after painting with new color.  Not sure how I can provide debug info. 
extra info - after clicking 'Closest' button - current color is added to history : 
![image](https://user-images.githubusercontent.com/13521338/147610722-332694a5-2bfa-4a15-93d0-cc2a1df9b5c3.png)
Update: 
After bit of testing : color  history is updated if I use build in  color picker  (however update is done too often - when I Left Click and drag my cursor over build-in color picker  then Pigment.o history if flooded with new colors. I feel it should be updated only when currently picked color is used to draw stroke ).

**Comment by EyeOdin** [comment]
Currently "History" registers only new Krita colors. This is on par with everything you report. This is all known limitations.
You "feel that it should be updated only when used" but there is no API to verify a "used color". This means this request is impossible to achieve until the API has the command for it. Krita developers are already aware of this need as it was already requested before by other users.
