### ISSUE TITLE
Krita doesn't launch after installing Pigment.O

### ISSUE THREAD

**Issue by codl** [EyeOdin/Pigment.O#8]
After installing and enabling Pigment.O, Krita displays an error on launch and closes.

<details><summary>Full traceback</summary>
<pre>TypeError
Python 3.10.1: /usr/bin/python3
Fri Jan 21 14:38:02 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'pigment_o.pigment_o_docker.PigmentO_Docker'>

 /home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py in __init__(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
  322         self.Harmonys()
  323         self.Color_ofthe_Day()
  324         self.Panels()
  325         self.Gamut()
  326         self.Dots()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Panels = <bound method PigmentO_Docker.Panels of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 /home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py in Panels(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
  572     def Panels(self):
  573         # Panel UVD
  574         self.panel_uvd = Panel_UVD(self.layout.panel_uvd)
  575         self.panel_uvd.SIGNAL_UVD_VALUE.connect(self.Signal_UVD)
  576         self.panel_uvd.SIGNAL_UVD_RELEASE.connect(self.Pigment_Display_Release)
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.panel_uvd undefined
global Panel_UVD = <class 'pigment_o.pigment_o_modulo.Panel_UVD'>
self.layout = <PyQt5.QtWidgets.QWidget object>
self.layout.panel_uvd = <PyQt5.QtWidgets.QWidget object>

 /home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py in __init__(self=<pigment_o.pigment_o_modulo.Panel_UVD object>, parent=<PyQt5.QtWidgets.QWidget object>)
  174         # Start
  175         self.Variables()
  176         self.Cursor()
  177         # Size Hint Expand
  178         self.setSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
self = <pigment_o.pigment_o_modulo.Panel_UVD object>
self.Cursor = <bound method Panel_UVD.Cursor of <pigment_o.pigment_o_modulo.Panel_UVD object>>

 /home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py in Cursor(self=<pigment_o.pigment_o_modulo.Panel_UVD object>)
  207         self.cursor_size = 20
  208         self.cursor_half = self.cursor_size / 2
  209         self.cursor_lmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
  210         self.cursor_rmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
  211         self.cursor_rmb.resize(0, 0)
self = <pigment_o.pigment_o_modulo.Panel_UVD object>
self.cursor_lmb = <PyQt5.QtSvg.QSvgWidget object>
self.cursor_lmb.setGeometry = <built-in method setGeometry of QSvgWidget object>
global QtCore = <module 'PyQt5.QtCore' from '/usr/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so'>
QtCore.QRect = <class 'PyQt5.QtCore.QRect'>
self.cursor_half = 10.0
self.cursor_size = 20
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...ct(QRect): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py", line 324, in __init__
    self.Panels()
  File "/home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py", line 574, in Panels
    self.panel_uvd = Panel_UVD(self.layout.panel_uvd)
  File "/home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py", line 176, in __init__
    self.Cursor()
  File "/home/codl/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py", line 209, in Cursor
    self.cursor_lmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'

</pre>
</details>

I'm using Arch Linux (btw) and this happens with the version of Krita in the arch package repositories, but not with the appimage build of krita available from krita.org. Coupled with the error, I suspect this to be an incompatibility with a newer version of a library.

I did read the note in the manual about PyQT5-SVG but, as far as I can tell, my copy of PyQt5 came with the SVG module included. I can import `PyQt5.QtSvg`, at least.

Additional version info:
Krita 5.0.2
Qt 5.15.2
PyQt5 5.15.6
Python 3.10.1

And, for reference, the appimage version (which works):
Krita 5.0.2
Qt 5.12.12
PyQt5 5.15.4
Python 3.8.1

**Comment by EyeOdin** [comment]
Then import the SVG module are your good.

**Comment by EyeOdin** [comment]
However the Panel UVD is currently running properly as it is healthy. this error not reproducible.
Which makes me think you have some issue wrong on your end to run this. This section of code is always a issue to people that do not have SVG installed properly. Also Arch Linux is reported to have issues with missing dependencies with Krita.

**Comment by EyeOdin** [comment]
However the Panel UVD is currently running properly as it is healthy. this error not reproducible.
Which makes me think you have some issue wrong on your end to run this. This section of code is always a issue to people that do not have SVG installed properly. Also Arch Linux is reported to have issues with missing dependencies with Krita.

**Comment by sbstratos79** [comment]
I am facing the exact same issue.

<details>
<summary>Log.</summary>
TypeError
Python 3.10.2: /usr/bin/python3
Thu Mar 10 16:56:19 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'pigment_o.pigment_o_docker.PigmentO_Docker'>

 /home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py in __init__(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
  322         self.Harmonys()
  323         self.Color_ofthe_Day()
  324         self.Panels()
  325         self.Gamut()
  326         self.Dots()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Panels = <bound method PigmentO_Docker.Panels of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 /home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py in Panels(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
  572     def Panels(self):
  573         # Panel UVD
  574         self.panel_uvd = Panel_UVD(self.layout.panel_uvd)
  575         self.panel_uvd.SIGNAL_UVD_VALUE.connect(self.Signal_UVD)
  576         self.panel_uvd.SIGNAL_UVD_RELEASE.connect(self.Pigment_Display_Release)
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.panel_uvd undefined
global Panel_UVD = <class 'pigment_o.pigment_o_modulo.Panel_UVD'>
self.layout = <PyQt5.QtWidgets.QWidget object>
self.layout.panel_uvd = <PyQt5.QtWidgets.QWidget object>

 /home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py in __init__(self=<pigment_o.pigment_o_modulo.Panel_UVD object>, parent=<PyQt5.QtWidgets.QWidget object>)
  174         # Start
  175         self.Variables()
  176         self.Cursor()
  177         # Size Hint Expand
  178         self.setSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
self = <pigment_o.pigment_o_modulo.Panel_UVD object>
self.Cursor = <bound method Panel_UVD.Cursor of <pigment_o.pigment_o_modulo.Panel_UVD object>>

 /home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py in Cursor(self=<pigment_o.pigment_o_modulo.Panel_UVD object>)
  207         self.cursor_size = 20
  208         self.cursor_half = self.cursor_size / 2
  209         self.cursor_lmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
  210         self.cursor_rmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
  211         self.cursor_rmb.resize(0, 0)
self = <pigment_o.pigment_o_modulo.Panel_UVD object>
self.cursor_lmb = <PyQt5.QtSvg.QSvgWidget object>
self.cursor_lmb.setGeometry = <built-in method setGeometry of QSvgWidget object>
global QtCore = <module 'PyQt5.QtCore' from '/usr/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so'>
QtCore.QRect = <class 'PyQt5.QtCore.QRect'>
self.cursor_half = 10.0
self.cursor_size = 20
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...ct(QRect): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py", line 324, in __init__
    self.Panels()
  File "/home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_docker.py", line 574, in Panels
    self.panel_uvd = Panel_UVD(self.layout.panel_uvd)
  File "/home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py", line 176, in __init__
    self.Cursor()
  File "/home/sbstratos79/.local/share/krita/pykrita/pigment_o/pigment_o_modulo.py", line 209, in Cursor
    self.cursor_lmb.setGeometry(QtCore.QRect(-self.cursor_half, -self.cursor_half, self.cursor_size, self.cursor_size))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
</details>
